OPENEJB-1063: Main-Class containing "/" instead of "." fails java.lang.NoClassDefFoundError: IllegalName
git-svn-id: https://svn.apache.org/repos/asf/openejb/trunk/openejb3@814528 13f79535-47bb-0310-9956-ffa450edef68