don't forget NoClassDefFoundError which is not an exception
git-svn-id: https://svn.apache.org/repos/asf/openejb/trunk@1333474 13f79535-47bb-0310-9956-ffa450edef68